/**
 * Created by waterflier on 2015/8/14.
 */

//鼠标
INPUTDEVICE_MOUSE = 1;
INPUT_ACTION_LBUTTON_DOWN  =1;
INPUT_ACTION_LBUTTON_UP    =2;
INPUT_ACTION_LBUTTON_DBCLICK =3;
INPUT_ACTION_RBUTTON_DOWN    =4;
INPUT_ACTION_RBUTTON_UP      =5;
INPUT_ACTION_RBUTTON_DBCLICK =6;
INPUT_ACTION_MBUTTON_DOWN    =7;
INPUT_ACTION_MBUTTON_UP      =8;
INPUT_ACTION_MBUTTON_DBCLICK =9;

INPUT_ACTION_MOUSE_MOVE      =10;
INPUT_ACTION_MOUSE_HOVER     =11;
INPUT_ACTION_MOUSE_ENTER     =12;
INPUT_ACTION_MOUSE_LEAVE     =13;

INPUT_ACTION_MOUSE_WHEEL     =14;


//按键-标准101键盘
INPUTDEVICE_STANDARD_KEYBOARD =2;
INPUT_ACTION_KEYBOARD_DOWN   =32;
INPUT_ACTION_KEYBOARD_UP     =33;
INPUT_ACTION_KEYBOARD_CHAR   =34;
INPUT_ACTION_KEYBOARD_HOTKEY =35;


//按键-标准设备按键
INPUTDEVICE_STANDARD_DEVICE_BUTTON =4;

//主触摸屏
INPUTDEVICE_MAIN_TOUCH_SCREEN =8;
INPUT_ACTION_TOUCH_DOWN =100;  //value x|y param:null data:null
INPUT_ACTION_TOUCH_MOVE  =101; //value x|y param:null data:null
INPUT_ACTION_TOUCH_UP   =102; //value x|y param:null data:null
INPUT_ACTION_TOUCH_ONE_DOWN =103; //value  x|y
INPUT_ACTION_TOUCH_ONE_UP =104; //value x|y